StudentsManagement/Controllers/AjaxDisplayByGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using StudentsManagement.Models;
using Newtonsoft.Json;
using System.Threading;

namespace StudentsManagement.Controllers
{
    public class AjaxDisplayByGroupController : Controller
    {
        private StudentsManagementEntities db = new StudentsManagementEntities();

        // GET: AjaxDisplayByGroup
        public ActionResult Index()
        {
            var registrations = db.Registrations.Include(r => r.Course).Include(r => r.Group).Include(r => r.User).Include(r => r.User1);
            return View(registrations.ToList());
        }

        [HttpPost]
        public ActionResult FirstAjax(string id)
        {
           
            var data = new { status = "ok", result = id};
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetStudentByGroup (string id)

        {
           
         

           var query = db.Registrations.ToList().Where(a => a.GroupId.ToString().Equals(id)).ToString();
            
            for(int i = 0; i < query.Count() ; i++)
            {

            }
            
            List<Registration> listreg = new List<Registration>();
           
            DataTable dt = new DataTable();
            dt.Columns.Add("Id", Type.GetType("System.Int32"));
            dt.Columns.Add("Group", Type.GetType("System.String"));
           
            
            string  data = JsonConvert.SerializeObject(query);
         

           // JSONString = JsonConvert.SerializeObject
          //  DataTable dtPersons = oDAL.GetTable();
        //    List<Dictionary<string, object>> lstPersons = query;
           // var data = DataTableToJSONWithJSONNet(data1);
           

            return Json(data, JsonRequestBehavior.AllowGet);
            //return Json(db.Registrations.ToList().Where(a => a.GroupId.ToString().Equals(id)));
           // return Json(db.Registrations.Where(x => x.GroupId.Equals(id)).ToList(), JsonRequestBehavior.AllowGet);

        }

       
        public JsonResult GetStudentByGroup1(string id)

        {
            
          
                
                List<Registration> studentList = new List<Registration>();
                studentList = db.Registrations.Where(a => a.GroupId.ToString().Equals(id)).ToList();
                for(int i = 0; i < studentList.Count(); i++)
            {
              /*  Registration student = new Registration
                {

                    StudentId = item.StudentId,
                    User = item.User,
                    Group = item.Group

                };
                studentList.Add(student);*/
            }
            
            var jsonSerializerSettings = new JsonSerializerSettings
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects
            };
            string data = Newtonsoft.Json.JsonConvert.SerializeObject(studentList, jsonSerializerSettings);
            var count = studentList.Count();
              /*  foreach (var item in studentList)
                {
                    Registration student = new Registration
                    {

                        StudentId = item.StudentId,
                        User = item.User,
                        Group = item.Group

                    };
                    studentList.Add(student);
                   
                   
                }*/
                
                // data = JsonConvert.SerializeObject(studentList);
                //var data1 = studentList.ToArray();
               // var data2 = data1[0].Group;
              

            return Json(count, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetStudentByGroup2(string id)

        {
            List<Registration> studentList = new List<Registration>();
            List<StudentByGroup> studentList1 = new List<StudentByGroup> ();
            studentList = db.Registrations.Where(a => a.GroupId.ToString().Equals(id)).ToList();
           
            foreach (var item in studentList)
            {
                StudentByGroup student = new StudentByGroup
                {

                    User = item.User,
                  
                    Group = item.Group

                };
                studentList1.Add(student);


            }
            

       var jsonSerializerSettings = new JsonSerializerSettings
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects
            };
            string data = Newtonsoft.Json.JsonConvert.SerializeObject(studentList1, jsonSerializerSettings);
  


            return Json(data, JsonRequestBehavior.AllowGet);

        }
        public string DataTableToJSONWithJSONNet(DataTable table)
        {
            string JSONString = string.Empty;
            JSONString = JsonConvert.SerializeObject(table);
            return JSONString;
        }
        /*     public JsonResult GetbyID(int ID)

             {

                 var Employee = empDB.ListAll().Find(x => x.EmployeeID.Equals(ID));

                 return Json(Employee, JsonRequestBehavior.AllowGet);

             }
        */

        // GET: AjaxDisplayByGroup/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // GET: AjaxDisplayByGroup/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Course1");
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "GroupName");
            ViewBag.StudentId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.TeacherId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: AjaxDisplayByGroup/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StudentId,GroupId,CourseId,TeacherId")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Registrations.Add(registration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Course1", registration.CourseId);
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "GroupName", registration.GroupId);
            ViewBag.StudentId = new SelectList(db.Users, "Id", "FirstName", registration.StudentId);
            ViewBag.TeacherId = new SelectList(db.Users, "Id", "FirstName", registration.TeacherId);
            return View(registration);
        }

        // GET: AjaxDisplayByGroup/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Course1", registration.CourseId);
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "GroupName", registration.GroupId);
            ViewBag.StudentId = new SelectList(db.Users, "Id", "FirstName", registration.StudentId);
            ViewBag.TeacherId = new SelectList(db.Users, "Id", "FirstName", registration.TeacherId);
            return View(registration);
        }

        // POST: AjaxDisplayByGroup/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StudentId,GroupId,CourseId,TeacherId")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "Id", "Course1", registration.CourseId);
            ViewBag.GroupId = new SelectList(db.Groups, "Id", "GroupName", registration.GroupId);
            ViewBag.StudentId = new SelectList(db.Users, "Id", "FirstName", registration.StudentId);
            ViewBag.TeacherId = new SelectList(db.Users, "Id", "FirstName", registration.TeacherId);
            return View(registration);
        }

        // GET: AjaxDisplayByGroup/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // POST: AjaxDisplayByGroup/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Registration registration = db.Registrations.Find(id);
            db.Registrations.Remove(registration);
            db.SaveChanges();

StudentsManagement/Controllers/DisplayGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using StudentsManagement.Models;

namespace StudentsManagement.Controllers
{
    public class DisplayGroupController : Controller
    {
        private StudentsManagementEntities db = new StudentsManagementEntities();

        // GET: DisplayGroup
        public ActionResult Index()
        {
            return View(db.Groups.ToList());
        }



        // GET: DisplayGroup/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // GET: DisplayGroup/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DisplayGroup/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,GroupName,Description")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        // GET: DisplayGroup/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: DisplayGroup/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,GroupName,Description")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        // GET: DisplayGroup/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: DisplayGroup/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentsManagement/Views/DisplayGroup/Create.cshtml
@model StudentsManagement.Models.Group

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentsManagement/Views/DisplayGroup/Delete.cshtml
@model StudentsManagement.Models.Group

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentsManagement/Views/DisplayGroup/Details.cshtml
@model StudentsManagement.Models.Group

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
 
    @Html.ActionLink("Back to List", "Index")
</p>

StudentsManagement/Views/DisplayGroup/Edit.cshtml
@model StudentsManagement.Models.Group

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentsManagement/Views/DisplayGroup/Index.cshtml
@model IEnumerable<StudentsManagement.Models.Group>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    Groups
</p>
<select id="group" name="group">
    <option value="">Group</option>
    @foreach (var item in Model)
    {

        <option value="@Html.DisplayFor(modelItem => item.Id)">
            @Html.DisplayFor(modelItem => item.GroupName)
        </option>



    }


</select>
<div id="result"></div>
<table id="listTable" class="table table-dark table-striped">
</table>
<div id="showResult"></div>
<div id="waitForIt" style="z-index: 2; position: absolute; top: 100px; left: 150px;">
    <img src="/images/swirl.gif" width="50">
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GroupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
               
                @Html.ActionLink("Details", "Details", new { id = item.Id }) 
               
            </td>
        </tr>
    }

</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>

    var currId = 0; // id of currently selected item, 0 if none
    var username = "", password = "";
    var sortOrder = "id";


    function selectItem(id) {
        $("#waitForIt").show();
        $.ajax({
            url: "/display_quizQuestion" + id,
            type: "GET",
            dataType: "json",
            headers: { 'X-auth-username': username, 'X-auth-password': password },
            error: function (jqxhr, status, errorThrown) {
                if (jqxhr.status == 403) {
                    loginFailedHandler();
                } else {
                    alert("AJAX error: " + jqxhr.responseText);
                }
            }
        }).done(function (todo) {
            currId = id;
            $("#currentId").html(todo.id);
            $("input[name=task]").val(todo.task);
            $("input[name=dueDate]").val(todo.dueDate);
            $("input[name=isDone]").prop('checked', todo.isDone == 'done');
            $("#saveOrAdd").html("Save changes");
            $("#viewAddEditPane").show();
        }).always(function () {
            $("#waitForIt").hide();
        });
    }


    $(document).ready(function () {

        $("#waitForIt").hide();

        $("#group").on('change', function () {

            console.log("group changed");
            $("#waitForIt").show();
            refreshTodoList();


        });



    });

    function loginFailedHandler() {
        alert("Authentication failed");
        $("input[name=username]").val("");
        $("input[name=password]").val("");
        $("#loginPane").show();
        $("#registerPane").show();
        $("#mainAppPane").hide();
    }

    function refreshTodoList() {
        $("#waitForIt").show();
        group = $("#group option:selected").text();
        groupId = $("#group option:selected").val();
        console.log(groupId,group);
        //para
        var serviceURL = '/ajax_display_by_groupController/FirstAjax';


            $.ajax({
                 type: "GET",
                url: '@Url.Action("GetStudentByGroup2", "AjaxDisplayByGroup")',
               //async: false,
               // cache: false,
                dataType: 'json',
                data: { id: groupId },
                contentType: 'application/json; charset=utf-8',
                success: successFunc,
                error: errorFunc
            });

        function successFunc(data) {
           

           
                var html = '';
            console.log("ajax ok");
           // console.log("data length", data.length);
                //alert(data.result,data.status);
                console.log('data=', data);
               // var dtPersons = eval(data);
               // displayJSONData(dtPersons);



            }

            function errorFunc() {
                alert('error1');
            }
    function displayJSONData(dtPersons) {
        var strColumnData1 = "";
        var strColumnData2 = "";
        var strColumnData3 = "";

        for (i = 0; i < 3; i++) {
            var divRow = document.getElementById("divRow_" + i);

            if (i < dtPersons.length) {
                strColumnData1 = dtPersons[i].StudentId;
                strColumnData2 = dtPersons[i].User;
                strColumnData3 = dtPersons[i].Group;
                alert(strColumnData3);
            }
            else {

            }

        }
    }

        return false;
    }

    function sortBy(order) {
        console.log("sorting by " + order);
        sortOrder = order;
        refreshTodoList();
    }
    //


    // just for demonstration purposes, do not use in production code
    function wait(ms) {
        var start = new Date().getTime();
        var end = start;
        while (end < start + ms) {
            end = new Date().getTime();
        }
    }


</script>